<header class="c-site-header" itemscope itemtype="http://schema.org/WPHeader">

		<h1 class="c-site-header__logo c-logo"><span class="c-logo__item">Open</span><span class="c-logo__item">-</span><span class="c-logo__item">Bracket</span></h1>

        <p class="c-site-header__tagline c-site-tagline">Web musing’s tutorials and news</p>

        {% include "site-nav.swig" %}

</header>
<!-- !END header.l-header -->