{% extends '../layout/default.swig' %}

{% block content %}
		
		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-overview.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-typography.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-headings.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-palette.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-forms.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-buttons.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-icons.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-modules.swig" %}

		</section>

		<section class="guide h-mb">

			{% include "../includes/components/pages/guide/section-helpers.swig" %}

		</section>

{% endblock %}